### ISSUE TITLE
gatlingRun doesn't run any simulations if the simulation files are not changed

### ISSUE THREAD

**Issue by behrangsa** [lkishalmi/gradle-gatling-plugin#100]
`gatlingRun` doesn't run any simulations if the simulation files are not changed.

Sometimes I tweak my web server and want to rerun the same simulation without changing it. Now I either have to run `clean gatlingRun` or make an immaterial modification to the simulations before the plugin can run them again.

**Comment by eshepelyuk** [comment]
You can also use `--rerun-tasks`, as described here
https://mrhaki.blogspot.com/2016/12/gradle-goodness-run-task-ignoring-up-to.html
