### ISSUE TITLE
Documentation should make clear the plugin's configuration requirements

### ISSUE THREAD

**Issue by markttaylor** [lkishalmi/gradle-gatling-plugin#102]
Three people at my work all independently hit the same issues with configuring their project and using the plugin.  The documentation should make it plain that:
a)
The source tree must conform to the default src/gatling/simulation structure else the simulations will not be found to run

b)
gradle.build must use the 'gatling' configuration in dependencies in order for the dependencies to be available within the simulation code.

**Comment by markttaylor** [comment]
This covers the issue: https://github.com/lkishalmi/gradle-gatling-plugin/issues/36

I made a pull request here: https://github.com/lkishalmi/gradle-gatling-plugin/pull/103

**Comment by eshepelyuk** [comment]
resolved
