### ISSUE TITLE
Remove -XX:+AggressiveOpts to support for java 13

### ISSUE THREAD

**Issue by AnnaDubrovinskaya** [lkishalmi/gradle-gatling-plugin#105]
Hello!

I have "Unrecognized VM option 'AggressiveOpts'" exception when running tests.

`echo $JAVA_HOME
../java/13.0.2-zulu
`
Is it possible to support Java 13 in your plugin? 
Thank you!

**Comment by eshepelyuk** [comment]
I need to release new version with changes from Gatling 3.3.1
Meanwhile - you can configure your plugin to use different JVM options, as described in README
https://github.com/lkishalmi/gradle-gatling-plugin#plugin-configuration

**Comment by AnnaDubrovinskaya** [comment]
@eshepelyuk thank you for your quick response and explanation!

**Comment by eshepelyuk** [comment]
A new version 3.3.0 is released, so you can try. 
Closing the issue.
