### ISSUE TITLE
When there are failed simulations the error message prints all simulations instead of just the failed simulations

### ISSUE THREAD

**Issue by anoopgarlapati** [lkishalmi/gradle-gatling-plugin#108]
I am using plugin version `3.3.1` and I observed that behavior of error message changed in a recent version. I have around 20 simulations as part of test suite and when there is a failure in one of them, the error message now reads "There're failed simulations: simulation1FQN, simulation2FQN, ..., simulation20FQN" when in fact only one simulation failed. This is tedious for us to check all the simulation reports to see which actually failed.
This used to work properly before where the error message was "Some simulations failed: failedSimulationFQN". 
I've tracked down the problem to an enhancement commit https://github.com/lkishalmi/gradle-gatling-plugin/commit/82ad702948c63baea6431ed3c37a10861d628f1d#diff-7bc60cc739fa8b7bb64a003d960de9ebR85-R86. If you now look at the marked lines, the message now logs all simulations instead of just failed simulations. I would like this behavior to be restored.

Thanks,
Anoop

**Comment by eshepelyuk** [comment]
Thnx @anoopgarlapati for the hint, seems as a regression.
I expect this to be fixed and released a new version in some days.

**Comment by eshepelyuk** [comment]
@anoopgarlapati release is plnned after fixing this one and #107 
join our gitter channel to receive new release announcement earlier ;)

**Comment by anoopgarlapati** [comment]
@eshepelyuk Thanks for the quick fix and release!
