### ISSUE TITLE
The default log level doesn't seem to be WARN

### ISSUE THREAD

**Issue by jonatan-ivanov** [lkishalmi/gradle-gatling-plugin#110]
Even is I explicitly set it, seemingly it has no effect, I still see `DEBUG` events.
```groovy
gatling {
    logLevel = 'WARN'
}
```

However, if I create a `logback.xml` in the resources folder, and set the level there, it works.

**Comment by eshepelyuk** [comment]
Please provide an output where you see debug logs

**Comment by eshepelyuk** [comment]
Created a sample project, following [quickstart](https://github.com/lkishalmi/gradle-gatling-plugin#quickstart)

Log levels works as expected, closing the issue.

**Comment by jonatan-ivanov** [comment]
@eshepelyuk What is the expected behavior for you?
Also, Is it just me, or were there other comments here that are missing now?

**Comment by eshepelyuk** [comment]
> @eshepelyuk What is the expected behavior for you?
**expected behaviour** is when something behaves according to predefined rules, i.e. works as expected.
With more clarification, I mean that this plugin's logging functionality override is working as described in README, i.e. `logLevel` from `gatling` section changes log level of `Gatling` logger.

> Also, Is it just me, or were there other comments here that are missing now?
yes there were, I've deleted them.

**Comment by jonatan-ivanov** [comment]
That wasn't really professional. If we have a language barrier, I'm sorry but it is hard for me to see good intentions in your comment.

Based on the README, the default `logLevel` is `WARN` but if you
1. Clone this repo: https://github.com/jonatan-ivanov/resourceater
2. Delete the `[logback.xml](https://github.com/jonatan-ivanov/resourceater/blob/master/perf-test/src/gatling/resources/logback.xml)`
3. Run `./gradlew gatlingRun`

you will see something like this, which seems more like `DEBUG` level than `WARN`:
```
11:33:54.480 [gatling-http-1-12] DEBUG io.gatling.http.engine.response.DefaultStatsProcessor - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
createObject: KO i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8080
=========================
Session:
Session(heapStress,107,1590258834478,Map(gatling.http.ssl.sslContexts -> SslContexts(io.netty.handler.ssl.ReferenceCountedOpenSslClientContext@28dec713,None), gatling.http.cache.dns -> io.gatling.http.cache.DnsCacheSupport$$anon$1@101063ab, gatling.http.cache.baseUrl -> http://localhost:8080),0,KO,List(),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$513/0x0000000800ff5840@62680913)
=========================
HTTP request:
POST http://localhost:8080/resources/objects
headers=
Accept: application/json
host: localhost:8080
content-type: application/json
byteArraysBody={ "size": "1KB", "ttl": "PT10S" }
=========================
HTTP response:
<<<<<<<<<<<<<<<<<<<<<<<<<
11:33:54.480 [gatling-http-1-12] DEBUG io.gatling.core.action.Exit - End user #107
11:33:54.480 [GatlingSystem-akka.actor.default-dispatcher-3] DEBUG io.gatling.core.controller.inject.Injector - End user #107
11:33:54.499 [GatlingSystem-akka.actor.default-dispatcher-2] DEBUG io.gatling.http.engine.tx.HttpTxExecutor - Sending request=createObject uri=http://localhost:8080/resources/objects: scenario=heapStress, userId=108
11:33:54.499 [GatlingSystem-akka.actor.default-dispatcher-2] DEBUG io.gatling.core.controller.inject.open.OpenWorkload - Start user #108
...
```

**Comment by eshepelyuk** [comment]
Hello @jonatan-ivanov 

Have you tried to follow `quickstart` section to create a sample project and run all the tests. 
Cause I did - and all worked. Just try to do it yourself and report if it failed for you.

If the code in your repository doesn't work, then 
- update to latest version of the plugin
- attentionaly review all the configuration guide and check if your project doesn't break them
- detect the suspicious parts and then, if bug still exists, report it, *detailly reporting all the differences* that are making the plugin behave wrong.
- sure, maybe there's a bug, but if i doubt that, if you followed the guide about how to create a project, layout etc

P.S. : @jonatan-ivanov  plz, don't ever blame any of OSS maitainer for professionalism. OSS maintainers are doing software *for free*, on their spare time. And them all are expecting more dedicated level of collaboration and attitude to the product while creating the issues and reporting bugs.

**Comment by jonatan-ivanov** [comment]
Hi @eshepelyuk,

I did create my perf-test based on the quick start (more accurately based on the `build.gradle` of the `sample-project`). Yeah, you mentioned you tried the sample project twice, and I get it works (I tried it too) but I don't think it proves that there is no issue and I don't think it is a reason to cause an issue without gathering more data or doing any kind of investigation (I can investigate this further if you ask me nicely).

I checked what you suggested:
- I'm using the same version as the `sample-project`
- I did not configure anything

I still think it is a bug, I was able to repro it with a very little modification on the `sample-project`, check it out: https://github.com/jonatan-ivanov/gradle-gatling-plugin/commit/d195e3480c214e6f9815fe926813be87731ac6eb
It seems if there is no resources folder or that folder is empty, the log level is `DEBUG` (or lower).
Could you please try it on your side to see what happens? Does the issue persist or is this only happening on my box?

@eshepelyuk, those PS are worth to answer:

P.S.: Please don't talk to your users like this. I don't think I blamed you or any OSS maintainers for professionalism. I think I expressed how I felt about your comments (I still feel the same way). If you felt I did blame you, I apologize, my intentions were good here: to help you to find a bug.
I'm an OSS contributor too, I'm doing this for free too on my spare time. If you expect me to collaborate more (I'm not sure what does the more dedicated level of attitude mean) just ask what you need me to do and if you ask nicely and I have time, I'm happy to help.

P.S. 2:
> while the project is it based on Gradle 6.4 - the project still has deprected, i.e. broken application of the plugin

It might be my English but I'm not sure I get this.

>build.gradle has unjustifed declarations of scala and galtling dependicies. why unjustified ? - because the plugin already provides all those declaractions, no need to repeat in build.gradle

Yeah, it was weird to me too, I needed to do this otherwise, the task just failed. I think it was because something in the dependency tree of the plugin defined a wildcard version and one of them was in a bad shape or wasn't resolved correctly or maybe it was just the weather (unfortunately I don't remember what exactly). It seems that the issue is now gone so I'm going to remove the explicit declaration of those dependencies. (I did not open an issue since I thought it will be gone soon but forgot to check again).

P.S. 3.: ;)

**Comment by jonatan-ivanov** [comment]
Oh I forgot: if the issue persists on your side too (see my demo: https://github.com/jonatan-ivanov/gradle-gatling-plugin/commit/d195e3480c214e6f9815fe926813be87731ac6eb), could you please reopen this issue?

**Comment by jonatan-ivanov** [comment]
fyi, from @eshepelyuk : 
>This should be addressed in upcoming releases of https://github.com/gatling/gatling-gradle-plugin.

https://github.com/lkishalmi/gradle-gatling-plugin/issues/111#issuecomment-691625575

**Comment by jonatan-ivanov** [comment]
This issue seems to be the same as these newer ones in the `gatling/gatling` repo:
- https://github.com/gatling/gatling/issues/3951
- https://github.com/gatling/gatling/issues/3946
