### ISSUE TITLE
gatlingRun can't be execute for two times if there is nothing change between them.

### ISSUE THREAD

**Issue by ElaineSepter** [lkishalmi/gradle-gatling-plugin#112]
When runing my script by gatlingRun, I have to change some code in Simulation file(may be add a log), or I have to switch another cmd.(use "gradlew gatlingRun" the first time and "gradle gatlingRun-ApiSimulation" the next time.) Or the execution will not be run and no error, just refer the picture. 
![image](https://user-images.githubusercontent.com/18164241/84107567-91e48680-aa50-11ea-85cb-db4aa5a68b1d.png)

**Comment by ElaineSepter** [comment]
I tried in cmd.exe, same with IDEA.

**Comment by eshepelyuk** [comment]
This is a duplicate. See #100 for workaround.

**Comment by ElaineSepter** [comment]
Thank you very much @eshepelyuk
