### ISSUE TITLE
Is the Latest Version Unavailable?

### ISSUE THREAD

**Issue by meck93** [lkishalmi/gradle-gatling-plugin#114]
It seems that even though version 3.3.4 is published on Gradle plugins site: https://plugins.gradle.org/plugin/com.github.lkishalmi.gatling - the plugin is actually not available when trying to resolve it: https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gatling/gradle-gatling-plugin/3.3.4/gradle-gatling-plugin-3.3.4.pom

I checked: https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gatling/gradle-gatling-plugin and it looks like the latest published version is 3.3.0. Is this correct or am I missing something? Thanks for the feedback and your great work on the plugin!

**Comment by eshepelyuk** [comment]
Hello @meck93 

Have you tried to generate a sample project, and run sample gatling simulation, as described in README ? It is using 3.3.4 

Didn't it work ?

**Comment by meck93** [comment]
Hey @eshepelyuk, thanks for the quick reply. I have tried out the sample-project that works perfectly fine. 

But I still don't understand why the plugins gradle repository doesn't show the latest version: https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gatling/gradle-gatling-plugin/

**Comment by eshepelyuk** [comment]
Hello, 

So, if everything works - I am closing the issue. Feel free to reopen if you see real issues with a plugin.
