### ISSUE TITLE
Not logging at default level (WARN)

### ISSUE THREAD

**Issue by ScottG489** [lkishalmi/gradle-gatling-plugin#115]
When I run the `gatlingRun` task it logs at what appears to be the DEBUG level. Here is all of the configuration I have done which may be relevant:

```
sourceSets {
    gatling {
        scala.srcDirs = ["src/test/performance/simulations"]
        resources.srcDirs = ["src/test/performance/resources"]
    }
}
```

What seems to be causing the problem is that I currently don't have anything in my resources dir (`"src/test/performance/resources"`). If I put an empty file in there then it logs at the default level (WARN) or if I configure the level in my build.gradle it will also then respect that.

**Comment by eshepelyuk** [comment]
Hello @ScottG489 

1. thnx for the report, it could be an options with logging, if you override default source pathes. This will be investigated. Great that you have a workaround for this.

1. as a clarification, may you detailly explain the need for overriding default simulations source directories ? this could help us to analyze customer needs

**Comment by ScottG489** [comment]
Hey @eshepelyuk,

Thanks for the quick response. Regarding # 2, I have split up my types of tests into multiple sub-directories of the test dir. So for instance my test dir structure would look something like:

`src/test/unit/`
`src/test/integration`
`src/test/performance`

And so on. Maybe there is a more standard way of doing this that I'm not aware of but I have made different source set configurations to accommodate this. Hope this helps clarify why I had to override the default directories.

**Comment by jonatan-ivanov** [comment]
This seems like the same issue as #110 and #111.
@ScottG489 Could you please check if this issue seems like a duplicate for you too?
(If so, I would close this and link it to the original issue.)

**Comment by eshepelyuk** [comment]
This should be addressed in upcoming releases of https://github.com/gatling/gatling-gradle-plugin.

Closing the issue.

**Comment by ScottG489** [comment]
Hey @jonatan-ivanov. Sorry for the delay getting to this. Thanks for pointing this out. This does in fact seem like the same issue as #110 and #111. Looks like this was already closed so I'll move further conversation to #111.

**Comment by jonatan-ivanov** [comment]
This issue seems to be the same as these newer ones in the `gatling/gatling` repo:
- https://github.com/gatling/gatling/issues/3951
- https://github.com/gatling/gatling/issues/3946

**Comment by jonatan-ivanov** [comment]
@ScottG489 No problem, it seems @eshepelyuk eventually realized that this is a problem. Thank you for the help, I was not really able to convince him in #110 and #111.

This is now tracked in the `gatling/gatling` repo (I linked them in my previous comment).
