### ISSUE TITLE
How can I debug my simulation class with gradle-gatling-plugin?

### ISSUE THREAD

**Issue by silviozanelato19** [lkishalmi/gradle-gatling-plugin#116]
Hi, 
I'm trying to debug my simulation class to understand how my code is working, but I can't find any information here on how to debug using the plugin.
Could someone help me understand how to debug using this plugin?

**Comment by eshepelyuk** [comment]
1. you should run your gatling simulation with remote debug enabled [example](https://www.jetbrains.com/help/idea/tutorial-remote-debug.html#d2e83)
1. to pass parameters from plugin - you should add values to `gatling.jvmArgs` as described in [README](https://github.com/lkishalmi/gradle-gatling-plugin#plugin-configuration)

**Comment by silviozanelato19** [comment]
Thanks @eshepelyuk for the quick answer. It solved my problem.
