### ISSUE TITLE
Irritations about versioning

### ISSUE THREAD

**Issue by Geooorg** [lkishalmi/gradle-gatling-plugin#119]
Hi, 

it looks like this plugin will be renamed/moved to the 'official' Gatling organisation https://github.com/gatling/gatling-gradle-plugin.
However, I'm now wondering about the versioning and which one is meant to be 'official':

Following the Gradle Plugin website https://plugins.gradle.org/plugin/io.gatling.gradle from August 26th, they have released a beta version.

Currently the documentations on both sites seem to be identical, saying that the plugin version follows the versioning of Gatling.

I'm missing a clear statement saying which of the plugins will become the official ones (and which one will become deprecated respectively).
Thanks for a short clarification 👍

**Comment by eshepelyuk** [comment]
Plz be patient, there should be an announcement from Gatling soon, as they are preparing to release.

Briefly, this repo will be deprecated. There will be _a single official_ plugin, supported by Gatling itself.

**Comment by slandelle** [comment]
@Geooorg FYI, this beta version was supposed to be removed, we just wanted to test the release infrastructure and have it validated by the Gradle portal administrators. We were planning to delete it (it looks like we have 7 days to delete it) but the Gradle portal people took so much time to validate that the deletion period expired.

The official announcement will come along with the upcoming Gatling 3.4.0 release.

**Comment by Geooorg** [comment]
Thanks @eshepelyuk and @slandelle for your immediate responses and clarification!
