### ISSUE TITLE
Add support for custom gatling configuration

### ISSUE THREAD

**Issue by atdi** [lkishalmi/gradle-gatling-plugin#14]
My proposal is to add a new folder to resources called conf and add this to gatlingRuntime classpath

**Comment by eshepelyuk** [comment]
For the sake of convenience, I'd suggest to modify the issue's title to smth like *Add support for custom gatling configuration*, since the scope of PR #15 is much wider than `Graphite` support and introduces generic way of overriding default `Gatling` configuration.

**Comment by atdi** [comment]
@eshepelyuk You are right. I've made the change.

**Comment by eshepelyuk** [comment]
Thanks. May I ask for including into PR updates for `README` in `Project Layout` section as well ?

**Comment by atdi** [comment]
Yes, I'll update also the README file.

**Comment by eshepelyuk** [comment]
New version 0.2.1 is available at [Gradle Plugins Site](https://plugins.gradle.org/plugin/com.github.lkishalmi.gatling)

**Comment by lkishalmi** [comment]
Is this issue closed then?

**Comment by atdi** [comment]
Yep
