### ISSUE TITLE
documentation on how to provide jvm args in command line

### ISSUE THREAD

**Issue by alexeyOnGitHub** [lkishalmi/gradle-gatling-plugin#17]
if I want to run "gradle gatling" with command line  params like "-Dserver.env=myenv -Dusers=10 -DdurationInMinutes=2 -DrampupTimeInMinutes=1", what's the syntax for those?

**Comment by eshepelyuk** [comment]
Are those parameters custom ones introduced by your code ?

**Comment by alexeyOnGitHub** [comment]
right, those are params I need to load in my test.
this is how I run this using maven:

    mvn integration-test -Dgatling.simulationClass='my.MySimulation' -Dserver.env=myenv -Dusers=10 -DdurationInMinutes=2 -DrampupTimeInMinutes=1

then the Scala test loads this param:

    val getNumUsers: Int = Option(System.getProperty(PROPERTY_NUM_USERS)).map(_.toInt).getOrElse(50)

**Comment by eshepelyuk** [comment]
This seems a plugin's missing feature. We have to fix it.

**Comment by AlexMAS** [comment]
Hello! Unfortunately, it hasn't not work since fixing #25. Is there other way to do it now?

**Comment by eshepelyuk** [comment]
@AlexMAS maybe this thread could help
https://github.com/lkishalmi/gradle-gatling-plugin/issues/33

**Comment by AlexMAS** [comment]
@eshepelyuk Thank you. I'm sorry, it was my mistake. I used `scala.util.Properties.envOrElse()` instead of `scala.util.Properties.propOrElse()`.
