### ISSUE TITLE
resources from /src/gatling/resources are not accessible to tsv() method using root path

### ISSUE THREAD

**Issue by alexeyOnGitHub** [lkishalmi/gradle-gatling-plugin#18]
I have this code in the test:

    val ownerIds = tsv("owner_ids." + serverEnvironment + ".tsv").circular

the file 'owner_ids.myenv.tsv' used to be in /src/test/resources and this worked fine with Maven.
(tsv is a standard Gatling feeder).

now, I had to move /src/test/resources to /src/gatling/resources to get rid of the plugin compile errors when switching to Gradle + this plugin, and now the file cannot be loaded: 

    java.lang.IllegalArgumentException: Could not locate feeder file; file owner_ids.myenv.tsv doesn't exist
        at io.gatling.core.feeder.FeederSupport$class.feederBuilder(FeederSupport.scala:47)
        at io.gatling.core.Predef$.feederBuilder(Predef.scala:32)

maybe I should just move /src/gatling/* back to /src/test/* ?

**Comment by eshepelyuk** [comment]
Since it's `Gatling` feeder it should be put to
* `src/gatling/resources/data` OR
* `src/gatling/data`

depending on directory layout you've chosen. 
Please check `README` for complete documentation about project layout.

**Comment by alexeyOnGitHub** [comment]
thank you, I'll give it a try when a new version of the plugin is ready (with gatling version fix + jvm params fix)
