### ISSUE TITLE
default logging level is too verbose: it prints binary output plus strings

### ISSUE THREAD

**Issue by alexeyOnGitHub** [lkishalmi/gradle-gatling-plugin#20]
I did not configure logging level for the gradle/gatling plugin. I see simulation output includes millions of lines in console like

> 
> 
> 18:22:18.901 [gatling-http-thread-1-4] DEBUG io.netty.handler.logging.LoggingHandler - [id: 0xa6cb35cf, L:/ip:62370 - R:ip:443] FLUSH
> 18:22:18.943 [gatling-http-thread-1-4] DEBUG io.netty.handler.logging.LoggingHandler - [id: 0xa6cb35cf, L:/ip:62370 - R:ip:443] RECEIVED: 123B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 48 54 54 50 2f 31 2e 31 20 32 30 31 20 43 72 65 |HTTP/1.1 201 Cre|

that seems excessive...
note: I don't see all this debug when running the same tests using gatling-maven-plugin.

I added src/gatling/resources/conf/logback.xml file with this contents:
```

﻿<?xml version="1.0" encoding="UTF-8"?>
<configuration>

	<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>%d{HH:mm:ss.SSS} [%-5level] %logger{15} - %msg%n%rEx</pattern>
			<immediateFlush>false</immediateFlush>
		</encoder>
	</appender>

	<!-- Uncomment for logging ALL HTTP request and responses -->
	<!-- 	<logger name="io.gatling.http.ahc" level="TRACE" /> -->
	<!--    <logger name="io.gatling.http.response" level="TRACE" /> -->
	<!-- Uncomment for logging ONLY FAILED HTTP request and responses -->
	<!-- 	<logger name="io.gatling.http.ahc" level="DEBUG" /> -->
	<!--    <logger name="io.gatling.http.response" level="DEBUG" /> -->

	<root level="WARN">
		<appender-ref ref="CONSOLE" />
	</root>

</configuration>
```

but I'm thinking maybe the default logging should be less verbose?

**Comment by eshepelyuk** [comment]
The only way to change a logging output of `Gatling` is via configuring `logback`.
This plugin doesn't adjust any logging configuration and completely relies on `Gatling` defaults.

I think this will be good idea to provide a dedicated section in `README` about configuring logging output. 

###### P.S.
Please note, that this plugin is not related to `Maven` plugin for `Gatling` and not intended to mimic its functionality.

**Comment by dimitarg** [comment]
I want to point out the default configuration defeats the purpose of usage, since most of the jvm time is spent flushing and synchronizing on java.io.PrintStream which creates a serious bottleneck and the tool is not able to saturate the servers under test at all.

**Comment by lkishalmi** [comment]
Hmm maybe if we generate a proper logback.xml from a template with configurable loglevel and set the default to WARN, then it could work...

**Comment by lkishalmi** [comment]
https://github.com/lkishalmi/gradle-gatling-plugin/commit/d2a765d1189c4c54870a96ea9fded548a8e9ee4d

**Comment by Gleeble** [comment]
Just to add a comment onto this, Despite this fix I had still been experiencing the original issue with my runs. It turns out that a separate library we were using was overriding the SLF4J binding from logback to log4j rendering the logback.xml file useless. Just wanted to mention in case anyone comes across this issue and can't figure out why this isn't working for them now.
