### ISSUE TITLE
gradle gatling not running any simulations

### ISSUE THREAD

**Issue by christianhuening** [lkishalmi/gradle-gatling-plugin#21]
Hi,

thanks for the awesome plugin!
Sadly 'gradle gatling' does not run any simulations for me but just compiles them.
'gradle gatling-SimFQN' however runs the specified tasks. I use the Gradle/maven layout, but also tried the gatling layout.

cheers
Christian

**Comment by christianhuening** [comment]
Ah ok, I just looked into the sources and found that all simulation files have to end with '*Simulation.scala'

**Comment by eshepelyuk** [comment]
Please look at [Plugin Config](https://github.com/lkishalmi/gradle-gatling-plugin#plugin-configuration) section.
You may adjust default behavior using `gatling.simulations` property.
