### ISSUE TITLE
Gatling-like layout does not work in Linux.

### ISSUE THREAD

**Issue by anyone-can-test** [lkishalmi/gradle-gatling-plugin#27]
Gatling-like layout does not work in Linux.
.scala files are not compiled.

In Windows, it works.
Standard Gradle/Maven layout works in Linux.

**Comment by lkishalmi** [comment]
Hmm, strange, we have functional test for that layout and it works.
Could you attach a sample project (or just it's layout) which is not working for you?

**Comment by anyone-can-test** [comment]
It is the layout, very simple.

/src
     /gatling/simulations/push
     /test/resources

**Comment by lkishalmi** [comment]
Please check your layout against the one in the samples: https://github.com/lkishalmi/gradle-gatling-plugin/tree/master/sample/gatling-layout

It seems you are using something different.

**Comment by eshepelyuk** [comment]
@anyone-can-test You can try release `0.4.1`. It contains fix for Issue #30 that maybe related to this one.

**Comment by lkishalmi** [comment]
Well, I use Gatling like layout on Linux and it is working fine.
Since no response from  @anyone-can-test in the last month, I close this issue. Fell free to reopen it if you experience this again and can provide some details as well.
