### ISSUE TITLE
Intellij IDEA integration

### ISSUE THREAD

**Issue by moritzzimmer** [lkishalmi/gradle-gatling-plugin#29]
In order to write gatling simulations in IDEA, I've added the following lines to _build.gradle_:

```
idea {
    module {
        testSourceDirs += project.file('src/gatling/scala')
        scopes.TEST.plus += [project.configurations.gatlingCompile]
        scopes.TEST.plus += [project.configurations.gatlingRuntime]
    }
}
```

Maybe this information is useful for others devs too and thus should be part of the _README_. What do you think? An even better approach would be to detect the idea plugin in your plugin and add the config automatically.

**Comment by eshepelyuk** [comment]
What version of IDEA do you use ? For me it just works by applying plugin and importing Gradle project (IDEA 2016.2.2)

**Comment by moritzzimmer** [comment]
IDEA 2016.2.2, with 0.4.0. I'm gonna try a fresh import without my config settings.

**Comment by eshepelyuk** [comment]
I've tried to create a sample project and import it to IDEA. 
Apparently, there's no need for any additional modifications to `build.gradle`. 

Can you try to rebuild the whole project just after importing to IDEA ?

**Comment by moritzzimmer** [comment]
For me neither scala nor gatling dependencies are added to the IDEA classpath without the declaration above. I'm using Intellij's *open...* dialog to import the project.

**Comment by eshepelyuk** [comment]
I've tried Gradle 3.0 and Gradle 2.14.1 with the latest version of the plugin (0.4.0).

When importing empty project (without any simulation and even without `src` folder) - I've experienced an issue when there were no `Scala class` option available in `New` menu of IDEA (an actual minor bug).

But in any case I had `gatling` and `Scala` dependencies added by IDEA. (https://i.imgur.com/scqdOrF.png)

**Comment by eshepelyuk** [comment]
Just tried IDEA 2016.2.3 and it works fine as well.

**Comment by rfelgent** [comment]
Hi,

I had similar problems like @moritzzimmer described. 

My environment:
- gradlew 2.5
- Intellij 15.0.6
- JDK 8
- Mac OSX

The configuration provided by @moritzzimmer did the trick.

**Comment by eshepelyuk** [comment]
Hi, is this issue still valid ?

**Comment by rfelgent** [comment]
What do you mean?

The Problem still persists with idea 2015. But the workaround helps...

**Comment by eshepelyuk** [comment]
Have you tried latest IDEA (2017) ?

**Comment by rfelgent** [comment]
We could close this ticket. But I suggest to update the document with the code snippet provided by @moritzzimmer

**Comment by eshepelyuk** [comment]
Would you like to create a PR for README update ?

**Comment by eshepelyuk** [comment]
Closing issue. Feel free to provide ant PRs to README.
