### ISSUE TITLE
[Feature Request]Make folders configurable

### ISSUE THREAD

**Issue by atomfrede** [lkishalmi/gradle-gatling-plugin#32]
It would be cool to make folders configurable (like in the official maven plugin):

``` xml
  <configFolder>${project.basedir}/src/test/resources</configFolder>
  <dataFolder>${project.basedir}/src/test/resources/data</dataFolder>
  <resultsFolder>${project.basedir}/target/gatling/results</resultsFolder>
  <bodiesFolder>${project.basedir}/src/test/resources/bodies</bodiesFolder>
  <simulationsFolder>${project.basedir}/src/test/scala</simulationsFolder>
```

I can see the advantage of a sane convention, but at least an option to configure paths would be very cool (I am considering this plugin to be included in jhipster generator instead of our own custom solution)

**Comment by atomfrede** [comment]
If there is interest in this feature I could try to prepare a merge request

**Comment by eshepelyuk** [comment]
+1 for PR :)

**Comment by eshepelyuk** [comment]
@atomfrede @lkishalmi Have you noticed that build is failing after merging #42

**Comment by lkishalmi** [comment]
Yes. I'm going to try to fix it tomorrow. I need some sleep now.

2017. szept. 5. du. 11:37 ezt írta ("Evgeny Shepelyuk" <
notifications@github.com>):

**Comment by eshepelyuk** [comment]
@lkishalmi I could help on weekends, 
@atomfrede maybe you can take a look too ?

**Comment by atomfrede** [comment]
@eshepelyuk @lkishalmi I just executed `gradle check` locally and it works fine, can somebody restart the travis build? The build for the PR was also green, looks like a travis error somehow.

**Comment by eshepelyuk** [comment]
Does `gradle check` includes `gradle test` ? Are you using `Gradle` wrapper for running the tests locally, because TravisCI used wrapper.

**Comment by atomfrede** [comment]
Yes gradle Check executes all tests. That's also what Travis is doing. Using the wrapper yes.

**Comment by eshepelyuk** [comment]
@atomfrede - the same from my side. all works locally

**Comment by lkishalmi** [comment]
All is working for me locally as well.

**Comment by eshepelyuk** [comment]
Good news, build is green now. Are you going to create a new release for this feature ?

**Comment by lkishalmi** [comment]
Yes. Soon.

**Comment by atomfrede** [comment]
👍 I will add your plugin to https://github.com/jhipster/generator-jhipster so you may see a raise in downloads and issues/questions. I also talked with @oehme about how to handle the deprecation warning when using gradle 4 (currently the plugin assumes one source folder. That api will be removed in gradle 5). Will try to provide a PR for that after the new release.

**Comment by atomfrede** [comment]
Release is available, so let's close this.
