### ISSUE TITLE
[Feature Request] gatlingTestCompile

### ISSUE THREAD

**Issue by jchomicki** [lkishalmi/gradle-gatling-plugin#34]
Currently, gatlingCompile is great for main project dependencies, but it is pretty hacky if you want to use test project dependencies. It would be nice to have something like gatlingTestCompile for this use-case. 

For example, I have integration tests in a separate project and would like to use the utils from that other project in my Gatling tests. Normally, I would be able to just do a `testCompile project(":project")` but it does not seem to be possible given the current functionality.

**Comment by eshepelyuk** [comment]
Hi,
I assume, you have a multi module project. What would happen if you try to use `gatlingCompile project(":project:")` ?

Second option, you may put your `Gatling` sources right into your integration test project. Since they are located in separate folder they won't interfere with other tests, and test sources will be automatically available for `Gatling` simulations ( this is existing plugin functionality)

**Comment by eshepelyuk** [comment]
Seems I've understand your issue. I assume your utility classes are located inside `test` sources of integration test project, right ?

It is a some sort of `Gradle` limitation. You can read more http://stackoverflow.com/questions/5644011/multi-project-test-dependencies-with-gradle

So, you can follow those Solutions, or you can put utility classes into non `test` source set, so `gatlingCompile` will work.

**Comment by lkishalmi** [comment]
Some additional information which could be useful. Since Gradle 2.14, there is an option to use inter project dependecnies with classifiers: https://docs.gradle.org/2.14/release-notes.html#support-for-inter-project-dependency-classifiers

```groovy
gatlingCompile project(path: 'project2', configuration: 'testRuntime')
```

**Comment by jchomicki** [comment]
Thanks for the information, but I've already implemented a test artifact configuration with a dependency classifier to get around the issue short-term. It just feels really hacky given that eclipse compiles the project fine with just the gradle dependency ```testCompile project(":project")```.

It's only the compilation through this gradle plugin that fails without creating a test artifact with one of the workarounds mentioned above.

**Comment by lkishalmi** [comment]
It seems then, that we did not get the problem. Would it be possible to create and zip a minimal project of your kind to demonstrate this issue?

**Comment by eshepelyuk** [comment]
Closing, fell free to reopen
