### ISSUE TITLE
gatlingRun fails when run inside Eclipse on Windows

### ISSUE THREAD

**Issue by avonengel** [lkishalmi/gradle-gatling-plugin#35]
The `gatlingRun` task fails on Windows if run from inside Eclipse, using Buildship. This is most likely due to the command line becoming too long for Windows to handle.
The execution will fail with
```
:gatlingRunError: Could not find or load main class <random text>
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gatlingRun'.
> Process 'command '<C:\Program Files\Java\jdk1.8.0_111\bin\java.exe>'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED 
```

@slandelle explains some of it [here](https://groups.google.com/d/msg/gatling/O0Ap0BZSJvI/E435U6ztAQAJ).

I was able to track down the problem to the fact that the GatlingRunTask copies all of the parent process' system properties to the GradleProject.javaExec call that runs the Gatling VM ([source](https://github.com/lkishalmi/gradle-gatling-plugin/blob/master/src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingRunTask.groovy#L24)). The JavaExec will append all those properties as `-Dkey=value` to the command line.  When launched from Eclipse, this will append all of Eclipse's launch options to the command line.
This directly relates to #23.

I tried to remove the line in question from GatlingRunTask, and the task then succeeds in Eclipse. Quite some tests of the gradle-gatling-plugin will fail, though (which is why I didn't open a pull-request for this).

**Comment by eshepelyuk** [comment]
Have you tried to override `gatlingRung` task properties ? I.e. to write smth like this in your `build.gradle` 

```
gatlingRun.systemProperties [:]
```

**Comment by avonengel** [comment]
@eshepelyuk Thanks for the suggestion. And sorry for the long delay - I missed the notification for some reason.

I don't recall if we tried your suggested workaround. We ended up building a JAR file using the application plugin, though.

**Comment by eshepelyuk** [comment]
Closing, feel free to reopen.
