### ISSUE TITLE
ConnectException on AWS EC2

### ISSUE THREAD

**Issue by mekuriam** [lkishalmi/gradle-gatling-plugin#39]
I'm seeing [this](https://groups.google.com/forum/#!topic/gatling/GSOaPPcbxtY) When running gatling on EC2 instances. Is there any plan to upgrade the gatling version?

**Comment by eshepelyuk** [comment]
Have you tried `gatling.toolVersion` parameter ?

**Comment by mekuriam** [comment]
Thank you, I missed that parameter. Switching to version 2.1.7 took care of it.

**Comment by eshepelyuk** [comment]
Great, so can you close an issue now ?

**Comment by mekuriam** [comment]
Thanks again
