### ISSUE TITLE
Changing default simulation directory structure

### ISSUE THREAD

**Issue by eduardomoroni** [lkishalmi/gradle-gatling-plugin#41]
Is there a way to put a custom directory to gatling simulations? 
My current dir structure: 
```
src
|_ main
|_ test
|_ integrationTest
|_ endToEndTest
|_ gatling
```

I want to change `gatling` dir to `performanceTest`, for instance.

**Comment by eshepelyuk** [comment]
You could try add this to your `build.gradle`
```
project.sourceSets {
    gatling {
        scala.srcDirs         = ...
        resources.srcDirs = ...
    }
} 
```

**Comment by eduardomoroni** [comment]
Hey @eshepelyuk thanks for your help.
I did your suggestion like this: 
```
project.sourceSets {
    gatling {
        scala.srcDirs = ['src/performanceTest/scala']
        resources.srcDirs = ['src/performanceTest/resources']
    }
}
```
Now I can "read" files from `src/performanceTest` and then files appears on `build/gatling` but I'm getting this error: `The requested class('......performanceTest.com.emoroni.loyalty.performance.PerformanceSimulation.scala') can not be found in the classpath or does not extends Simulation.
There is no simulation script. Please check that your scripts are in user-files/simulations
`

Sorry I'm kinda new on gradle, gatling and stuff. Some considerations:
- My simulations are under `com.emoroni.loyalty.performance` package
- I tried to follow both folder structures conventions as README suggest, adapting to having `performanceTest/` as parent folder.

How could I make the [self.getClasspath](https://github.com/lkishalmi/gradle-gatling-plugin/blob/master/src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingRunTask.groovy#L44) point to correct folder? 

![image](https://cloud.githubusercontent.com/assets/823150/24804197/103ef092-1b84-11e7-8b8a-b8fc4cb2a19a.png)
![image](https://cloud.githubusercontent.com/assets/823150/24804210/19a708cc-1b84-11e7-9a19-01815b64235d.png)

**Comment by eshepelyuk** [comment]
Well, I do recommend to stick to default structure :)
There's no good way of changing default directory structure now :(

**Comment by eduardomoroni** [comment]
Sounds good buddy, I appreciate your help.
