### ISSUE TITLE
stackoverflow error

### ISSUE THREAD

**Issue by shrestha-s** [lkishalmi/gradle-gatling-plugin#44]
Hi all, 

I'm running into an issue where adding some checks for empty strings in the fields contained in JSON response seems to cause a StackOverflow error when compiling gatling through gradle (specifically in gatling CompileScala task).

I have verified that the fields are present in the JSON response. If I remove the checks for empty fields, the gatling tests pass. It seems strange to me that adding these checks would cause a stackoverflow error.

For e.g:
                .check(jsonPath("$.Y.guid.identifier").ofType[String].is("${uidToSearch}"))
                .check(jsonPath("$.Y.xyz1").ofType[String].is(""))
                .check(jsonPath("$.Y.xyz2").ofType[String].is(""))
                .check(jsonPath("$.Y.xyz3").ofType[String].is(""))
                .check(jsonPath("$.X.abc1").ofType[Int].is(-1))
                .check(jsonPath("$.X.abc2").ofType[String].is("Name of well #1"))
                .check(jsonPath("$.X.abc3").ofType[String].is("${uidToSearch"))
                .check(jsonPath("$.X.abc4").ofType[String].is(""))
                .check(jsonPath("$.X.abc5").ofType[String].is(""))

Following is the gatling plugin used in gradle:

plugins {
    id 'com.github.lkishalmi.gatling' version '0.4.1'
}

Thanks

**Comment by eshepelyuk** [comment]
So, this code works fine if running simulations from command line ?
I.e. without this plugin.

**Comment by shrestha-s** [comment]
Code works fine if I move the checks for empty String to a different scala file.

Initially it was running from a scala test file which was running 14+ exec (1 http query in each exec) and around 130+ checks. And it was failing during the compileGatlingScala stage. I moved it to another scala test file, which is running 1 exec and 60 checks.

**Comment by eshepelyuk** [comment]
Unfortunately those details are not sufficient for being able to start investigation if this is a plugin's fault,
So could you please provide following

1. update to latest `0.7.1` version and try your code to see if it works
1. download standalone `Gatling` distributiton from https://gatling.io/download/ and try your simulations without plugin
