### ISSUE TITLE
Plugin causes a deprecation warning when used with Gradle 4.3

### ISSUE THREAD

**Issue by erdi** [lkishalmi/gradle-gatling-plugin#51]
The plugin causes the following deprecation warning when used with Gradle 4.3:

> Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0

The offending line is apparently [GatlingRunTask.groovy:19](https://github.com/lkishalmi/gradle-gatling-plugin/blob/1c98b2dff5eaba6dea20744d5b74fbb4a9107d76/src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingRunTask.groovy#L19).

**Comment by eshepelyuk** [comment]
Hi, are you willing to provide a PR ?

**Comment by erdi** [comment]
Sure thing. It won't be instant, though.

**Comment by eshepelyuk** [comment]
You're welcome, absolutely no probs :)

**Comment by ysb33r** [comment]
I looked at it after @erdi pointed me at the issue. PR #52 solves the problem in a better way than the curent hack.
