### ISSUE TITLE
How do i change/override the default timeout configs in this plugin?

### ISSUE THREAD

**Issue by thivyae** [lkishalmi/gradle-gatling-plugin#59]
How do i change/override the default timeout configs in this plugin?
I agve ./gradlew gatlingRun-testSimulation -Dgatling.http.requestTimeout=120000
It didt get picked up.
Thoughts on how to pass gatling.http conf parameters from commandline?

**Comment by eshepelyuk** [comment]
@thivyae this parameter can be configured via `gatling.conf`. Please refer to [Gatling default config](https://github.com/gatling/gatling/blob/master/gatling-core/src/main/resources/gatling-defaults.conf) and #73 for details
