### ISSUE TITLE
how to launch gatling recorder

### ISSUE THREAD

**Issue by rahulmr** [lkishalmi/gradle-gatling-plugin#60]
There is an option to launch gatling recorder in the `gatling-maven-plugin` like `mvn clean gatling:recorder`.
I see no examples or issues to launch gatling recorder in the gradle plugin.
A guide could be helpful.
Thanks

**Comment by eshepelyuk** [comment]
Hello, @rahulmr there's no support for this feature in the plugin

**Comment by iwx1** [comment]
Is it possible to implement?

**Comment by rahulmr** [comment]
Is it possible to implement?

**Comment by eshepelyuk** [comment]
Totally possible, I suppose. Are you willing to provide a PR ?
