### ISSUE TITLE
Exclude sourceSets.main.output and sourceSets.test.output from gatlingRuntime/gatlingCompile

### ISSUE THREAD

**Issue by alisiikh** [lkishalmi/gradle-gatling-plugin#61]
Hello,

Great plugin, using it for a long time so far, works pretty well!

But I have one issue with it now. 

I have 2 `application.conf` files in both `src/main/resources` and `src/gatling/resources`, and it's quite reasonable as gatling is a standalone app. In Gradle 4.1 it was working fine because `src/gatling/resources` was the first in the classpath order, but after upgrade to Gradle 4.7 it's no longer so, now the `src/main/resources` is the first in the classpath and so `application.conf` is taken from it, but it fails to resolve as it requires ENV variables which of course are not provided by Gatling since Gatling has totally different `application.conf` and totally different goal.

My question is, why do you add the `sourceSets.main.output` and `sourceSets.test.output` as dependencies to the gatlingCompile configuration in the plugin class? This is weird, because gatling is not supposed to use any of those classes and resources, it's supposed to be used on it's own, e.g. it's supposed to run performance tests that are not related to business logic.

If the developer really needs sources from the other sourceSet let him decide whether to add them or not.

So I'd really vote for removing of the lines https://github.com/lkishalmi/gradle-gatling-plugin/blob/master/src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingPlugin.groovy#L81
```groovy
project.dependencies {
    gatlingCompile project.sourceSets.main.output
    gatlingCompile project.sourceSets.test.output
    ...
}
```

Please let me know what you think about that, also if somebody knows how to revert these two dependencies in my build.gradle, I'd really appreciate that!

Thank you guys! :)

**Comment by alisiikh** [comment]
Please see #62

**Comment by eshepelyuk** [comment]
There's  a reason behind including `main` and `test` source sets. 
It's very useful to reuse data provisioning code that is developed in tests. Image a microservice project in scala / java where tests containing a lot of helper classes for preparing the data for functional testing and then performance tests can reuse those helpers to prepare the same data but for stress testing.

Thanks for a PR, but I'd propose to keep the current behavior as a default and introduce a flag that will switch it off.

**Comment by alisiikh** [comment]
But why not to leave this decision to developer? I feel it's bad that plugin makes this decision for developer, I personally would like just to include stuff I want explicitly by myself.

**Comment by eshepelyuk** [comment]
The exact reasoning for this behavior is in my previous message.
Moreover, each `Gradle` plugin makes decisions for developers providing pre-configured things based in mostly convenient use cases.

**Comment by alisiikh** [comment]
The massive problem arises on `resources` management, since both main and test resources will be available for gatlingRuntime:

Having `logback.groovy` or actually any logback configuration in `main/resources` and let's say having a different configuration in `gatling/resources`, as it's obvious they should be different in most cases.

Since the output of the main sourceSet is added to `gatlingCompile`, I'd get `logback.groovy` setup and potentially other conflicts with resources, such as *.conf files, META-INF specific files, etc.

So I would disagree, this is inconvenient IMO :)

Of course I managed to hotfix this problem, but I think solution is ugly and inconvenient:
https://discuss.gradle.org/t/exclude-a-transitive-file-from-classpath-added-by-3rd-party-plugin/28575

**Comment by eshepelyuk** [comment]
Merged PR, let's wait for @lkishalmi to make a release.
