### ISSUE TITLE
Update plugin to support Gatling 3.0.0

### ISSUE THREAD

**Issue by olisikh** [lkishalmi/gradle-gatling-plugin#64]
Hello,

There's a new version out, can we align the plugin to support it?
Basically plugin partially supports the new version as the CLI has changed, here are the links just to compare:
https://gatling.io/docs/3.0/general/configuration/
https://gatling.io/docs/2.3/general/configuration/

**Comment by marcguilera-casumo** [comment]
RC2 is out. Is there any progress?

**Comment by alisiikh** [comment]
Looks like guys no longer support this plugin :(

**Comment by eshepelyuk** [comment]
I'll try to take a look how hard it will be to migrate to `3.x` version. Let you know this week.

**Comment by eshepelyuk** [comment]
A single functional test left to fix. I do hope, it's a matter of days to push new version ot Git.

**Comment by lkishalmi** [comment]
I'd like to bump the major version number of the plugin to 3 as well and keep it synced to the Gatling major version. I also branched master to support 0.7.x for a while, if nothing more than it's documentation would be useful.

**Comment by eshepelyuk** [comment]
Nice idea, plz do the changes needed.

**Comment by alisiikh** [comment]
@eshepelyuk sure, will try it, but it'd take some time, thank you!

**Comment by marcguilera-casumo** [comment]
Are we pushing it to the repo?

**Comment by eshepelyuk** [comment]
It's already pushed to `master`

**Comment by marcguilera-casumo** [comment]
Yes, but shouldn't he have 0.8.0 in https://plugins.gradle.org/plugin/com.github.lkishalmi.gatling ?

**Comment by eshepelyuk** [comment]
We will have as soon as @lkishalmi will finish some improvements and make a release.

**Comment by eshepelyuk** [comment]
With closure of #67 I think we're ready to release a new version with Gatling 3 support

**Comment by eshepelyuk** [comment]
3.0.1 is released, Grab it while it hot :)
@alisiikh @marcguilera-casumo
