### ISSUE TITLE
Gatling version validation.

### ISSUE THREAD

**Issue by eshepelyuk** [lkishalmi/gradle-gatling-plugin#67]
Since the plugin has a configuration parameter `toolVersion` it can be configured to use unsupported version of `Gatling`.

To prevent this I'd like to introduce a version validation to, i.e. ensure that plugin can't be configured to use unsupported version.

Another approach to prevent such misbehavior is to remove `toolVersion` at all.

@lkishalmi what do you think ?

**Comment by lkishalmi** [comment]
Agreed. I've already have the code, for that, just missing some tests for it.
I hope I can make it in the next few days.
