### ISSUE TITLE
How can output directories be parameterized?

### ISSUE THREAD

**Issue by undera** [lkishalmi/gradle-gatling-plugin#70]
Hi,
I used to use Gatling with specifying `-rf` and `-on` options. I'm now trying to use this plugin and I have found no way to configure these options via plugin parames in `groovy.build` file.  
Can you add this feature? Or is there existing way to pass those options via `groovy.build` syntax?

**Comment by eshepelyuk** [comment]
Hello,

1. `-rf` option never was configurable via plugin's settings, Now it's defaulted to `build/reports/gatling` as a default location for all `Gradle` reports
1. There's no option `-on` in `Gatling`, according to [their documentation](https://gatling.io/docs/current/general/configuration/)

**Comment by eshepelyuk** [comment]
I assume, the issue could be closed @undera ?
