### ISSUE TITLE
Error in Windows command execution

### ISSUE THREAD

**Issue by tarunkumard** [lkishalmi/gradle-gatling-plugin#71]
Execution failed for task ':gatlingRun-simulations.RuntimeParameters'

Trying to execute test from command line,it is to be noted this test passed with MyGatlingRunner class ,but failing at command line,below is console log

PS C:\Gating\gatling-fundamentals-projectStart-master> ./gradlew gatlingRun-simulations.RuntimeParameters

> Task :gatlingRun-simulations.RuntimeParameters FAILED
Error: Could not find or load main class Files

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gatlingRun-simulations.RuntimeParameters'.
> Some simulations failed : simu

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
3 actionable tasks: 1 executed, 2 up-to-date
PS C:\Gating\gatling-fundamentals-projectStart-master>

![image](https://user-images.githubusercontent.com/29559232/48072763-22325980-e192-11e8-8783-80f1a392f41a.png)

**Comment by eshepelyuk** [comment]
Please attach the sample project to reproduce the bug with minimal files required.

**Comment by TarunKDas2k18** [comment]
https://github.com/tarunkumard/gatling-fundamentals-projectStart-master/blob/master/scala/simulations/RuntimeParameters.scala

**Comment by TarunKDas2k18** [comment]
Here is the application to which load testing is performed

https://github.com/TechieTester/gatling-fundamentals-projectStart

**Comment by eshepelyuk** [comment]
Thnx, will try to spend some time this weekend.

**Comment by eshepelyuk** [comment]
Hmm, can you add not just the simulation file , but entire ptoject structure that can be run locally and reproduce the issue.

**Comment by tarunkumard** [comment]
Hey update ,I was able to fix this by using Java 8 instead of 11,I think we
can close the issue

**Comment by eshepelyuk** [comment]
Clos8ng
