### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: CSV headers can't be empty

### ISSUE THREAD

**Issue by cksanders** [lkishalmi/gradle-gatling-plugin#72]
On upgrading from 0.7.4 to 3.0.1 the following error is thrown `Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: CSV headers can't be empty`

Path of feeder: /src/gatling/resources/data/users.csv

Invoking feeder: def userFeeder = csv("data/users.csv").circular

I tried moving the csv to `/src/gatling/resources/users.csv`, however no luck; hoping you may know the solution?

Thanks.

**Comment by eshepelyuk** [comment]
Plz attach your CSV

**Comment by cksanders** [comment]
https://drive.google.com/file/d/1nvu3uHWXI3_BzQAT460HYb3PH2PQcC_F/view?usp=sharing

**Comment by eshepelyuk** [comment]
Have you tried to remove comma `,` from all the strings ?

**Comment by eshepelyuk** [comment]
@cksanders any news ? Otherwise gonna close the issue soon.

**Comment by eshepelyuk** [comment]
Closing because of missing feedaback, plz free to reopen if any news appear.
