### ISSUE TITLE
Provide documentation for adding custom gatling.conf

### ISSUE THREAD

**Issue by shubhamagarwal3010** [lkishalmi/gradle-gatling-plugin#73]
I want to use my gatling.conf file to configure gatling run cases. I have to enable graphite in my gatling.conf. How do I point to my gatling.conf

**Comment by eshepelyuk** [comment]
@shubhamagarwal3010 have you tried to put `gatling.conf` file to `src/gatling/resources` ?

**Comment by shubhamagarwal3010** [comment]
No I have not, will it do it?

**Comment by eshepelyuk** [comment]
I'll add this to documentaions section, thanks for opening an issue. 
Let it be open until docs will be fixed.
