### ISSUE TITLE
Support for functional specs

### ISSUE THREAD

**Issue by sathyakumarseshachalam** [lkishalmi/gradle-gatling-plugin#75]
Provide support for running gatling functional tests as specified here - https://gatling.io/docs/2.3/general/functional_specs

**Comment by alisiikh** [comment]
I think if you want to write and run functional tests using Gatling, you can just take this project as an example https://github.com/gatling/gatling-funspec-demo/

You'll need just three dependencies for your testCompile configuration along with scala plugin enabled and scala library being in compile classpath:

```gradle
apply plugin: 'scala'

dependencies {
  compile 'org.scala-lang:scala-library:2.12.7'

  testCompile 'org.scalatest:scalatest_2.12:3.0.5',
  testCompile 'io.gatling.highcharts:gatling-charts-highcharts:3.0.1',
  testCompile 'io.gatling:gatling-test-framework:3.0.1'
}
```

I'm afraid this plugin is only for running performance tests, and you actually don't need a plugin to run functional tests using gatling-framework.

**Comment by eshepelyuk** [comment]
@alisiikh plugin will support this. Just need some time to start working on the feature. @sathyakumarseshachalam meantime you can just add scala test into gatling dependencies.

**Comment by eshepelyuk** [comment]
In fact I believe this will be solved by just providing proper documentation of how to do it.
