### ISSUE TITLE
Created Docker image based from your project but docker run throws Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by TarunKDas2k18** [lkishalmi/gradle-gatling-plugin#79]
Dear Team,

I have created Docker image based from your project but docker run throws Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain.Here is dockerfile if you want to debug and run and help me in fixing this error

FROM openjdk:8-jdk-alpine

WORKDIR /opt

RUN wget -q https://services.gradle.org/distributions/gradle-3.3-bin.zip  \
    && unzip gradle-3.3-bin.zip -d /opt \
	&& rm gradle-3.3-bin.zip 

RUN echo "$PWD"
		
RUN apk add git
    
RUN git clone https://github.com/TechieTester/gatling-fundamentals.git

RUN echo "$PWD"

RUN cp -vif /opt/gatling-fundamentals/gradlew /opt/gradle-3.3/bin/

RUN mv -vif /opt/gatling-fundamentals/src/* /opt/gradle-3.3/bin/

RUN find /opt/

RUN chmod 777 /opt/gradle-3.3/bin/gradlew

ENV GRADLE_HOME /opt/gradle-3.3
ENV PATH $PATH:/opt/gradle-3.3/bin

Once docker image created locally try to run with below command 
Mind you i have given full access to gradlew using chmod 777 gradlew
You will get an error saying below...please help

PS C:\Gatling2\gatling6games> docker run --rm  -w /opt/gatling-fundamentals/ fromscratch4:local  sh -c  "gradle wrapper | gradlew gatlingRun simulations.RuntimeParameters"
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by marcguilera** [comment]
I used shadowJar to create a fat jar and use that from docker.
