### ISSUE TITLE
[Feature request] Do we have a way to skip a simulation?

### ISSUE THREAD

**Issue by ClifftonK** [lkishalmi/gradle-gatling-plugin#82]
I am checking if we have a way of skipping a simulation using this plugin when running all simulations using `gatlingRun`. I am running all simulations in my testing framework but would like to skip some simulations because they do not meet some conditions. I am looking for something that could do this.

Hint -> same thing we have in TestNG annotation @Test(enabled = false)

**Comment by eshepelyuk** [comment]
For now you can achieve this by using `gatling.simulations`

https://github.com/lkishalmi/gradle-gatling-plugin#examples

**Comment by ClifftonK** [comment]
I am already using that. But the thing is, i package my code to run on different test environments. i already have it in `gatling.simulations` but what i want is to skip it on some environments and run it on others. currently, i am exiting the execution using this,
```if (System.getProperty("env").contains("dev")) {
    System.err.println("ERROR: This simulation cannot be run for DEV. Exiting!")
    System.exit(-1)
  }```
 which makes it abort execution thereby not running other simulations

**Comment by eshepelyuk** [comment]
Why don't you put this logic to `build.gradle` ?

```
if (System.properties['env'] ~= 'dev`') {
gatling.simulations = ...
} else {
gatling.simulations = ...
}
```

**Comment by eshepelyuk** [comment]
Anyway, the proposal as you'd like to see it, should be addressed to core `Gatling` since this plugin is a just a wrapper around their runner. So if core runner will support this way of skipping simulations, this plugin will automatically pick that feature.

**Comment by ClifftonK** [comment]
Makes sense. Thanks @eshepelyuk for the suggestion. I will raise it with gatling.
