### ISSUE TITLE
Ignore test failures for Test Automation projects

### ISSUE THREAD

**Issue by mikhail-g** [lkishalmi/gradle-gatling-plugin#84]
When using Gatling in Test Automation project, the build must be successful what indicates that tests were run and the test report was generated correctly. If there're some test failures it will be shown in a report and in a command line output but only as a warning.

Please have a look at Gradle AbstractTestTask, there is `boolean ignoreFailures` field that affects handleTestFailures(), it would be great to have something like this here

**Comment by eshepelyuk** [comment]
Hello, 

I believe that tests must fail if smth fail, and never swallow the exception, but delegate handling of failures to CI / CD pipelines.

But if you're ready to contribute - plz welcome. Just have in mind that currently `GatlingRunTask` is not extending `AbstractTestTask` and probably will not extend in near future, unless you do contribute and make deep refactoring.

**Comment by eshepelyuk** [comment]
Hello

1. I believe that plugin should be responsible for running `Gatling`, gathering results and signal failure if one of `Gatling` return status is non-zero
1. this behavior is aligned with common behaviour of all tests runners, like JUnit, TestNG, etc
1. I believe that exception swallowing should be delegated to CI \ CD pipelines and not `Gradle` plugin (ie test runner)
1. the behaviour you described may be achieved if you remove `assertions` block from your simulations, so they will pass always and you wil lbe able to examine reports for failures.

Closing this as `won't fix`
