### ISSUE TITLE
Fail gradle task if any KO

### ISSUE THREAD

**Issue by sdelamo** [lkishalmi/gradle-gatling-plugin#85]
I want to fail the gatlingRun gradle task if the simulation fails. 

I created a file:

`buildSrc/src/main/groovy/com/github/lkishalmi/gralde/gatling/GatlingUtils.groovy` 

```groovy
package com.github.lkishalmi.gradle.gatling

import groovy.transform.CompileStatic

@CompileStatic
class GatlingUtils {

    static int numberOfKOs(String gatlingReportDir) {
        String latestReportFolderName = (new File(gatlingReportDir).listFiles() as List<File>).collect { it.name }.sort { a, b -> b <=> a }.get(0)
        int numberOfKOs = 0
        new File("${gatlingReportDir}/${latestReportFolderName}/simulation.log").eachLine { line ->
            if (line.contains("KO")) {
                numberOfKOs ++
            }
        }
        numberOfKOs
    }
}
```
Then configured `gatlingRun` to fail if KOs greather than a threshold (0 in my example). 

```groovy
gatlingRun {
    ext {
        gatlingReportsFolder = "${project.reportsDir}/gatling"
        koThreshold = 0
    }
    doLast {
        int numberOfKOs = com.github.lkishalmi.gradle.gatling.GatlingUtils.numberOfKOs(gatlingReportsFolder)
        if (numberOfKOs > koThreshold) {
            throw new GradleException("max KO allowed ${koThreshold}, got ${numberOfKOs}".toString())
        }
    }
}
```

is there a better way to fail the gradle task if the simulation fails?

If not it maybe good to add similar functionality to the plugin.

**Comment by lkishalmi** [comment]
Interesting approach. Could you create a PR for this feature?

**Comment by slandelle** [comment]
IMHO, this is a super bad idea:

1. Gatling’s log file is an internal. Don’t go complaining if we change format.
2. Failing run on such criteria is exactly what assertions are about.

**Comment by mattdkerr** [comment]
@slandelle Is there another way to do this? It's not particularly helpful to only leave negative feedback without any suggestions. This is a big issue for me as well, it's causing all kinds of false positive pipeline failures.

**Comment by slandelle** [comment]
@mattdkerr Without any suggestion?! I've explained that we provide a built-in mechanism for failing run based on stats: [assertions](https://gatling.io/docs/current/general/assertions/#assertions).

> Then configured gatlingRun to fail if KOs greater than a threshold (0 in my example).

```scala
global. failedRequests.count.is(0)
```

**Comment by mattdkerr** [comment]
Thank you for the link and additional detail.

**Comment by eshepelyuk** [comment]
@sdelamo this should work already. GatlingRun throws exception if any of simulation failed in thr latest releases ( 3.x) Could you check if it works for you ?

**Comment by eshepelyuk** [comment]
closing, feel free to reopen
