### ISSUE TITLE
Can't move simulation-responses.log to buildDir

### ISSUE THREAD

**Issue by mattdkerr** [lkishalmi/gradle-gatling-plugin#89]
It seems to be hard-coded to `target` subdirectory, regardless of what you set buildDir to in the gatling configuration block. There's no obvious way to fix this, unfortunately.

**Comment by eshepelyuk** [comment]
1. There's no `target` subdirectory in `Gradle`
2. `gatling` block doesn't support `buildDir` parameter.  
3. [The documentantion](https://github.com/lkishalmi/gradle-gatling-plugin#plugin-configuration) has no mentions about it.

Moreover, all gatling output is stored under `${reportDir}/gatling` so it follows the `Gradle` conventions.

Excuse me, but I don't understand the issue at all. Closing it. 

Feel free to reopen with comprehensive description and step to reproduce.
