### ISSUE TITLE
Make simulations source configurable

### ISSUE THREAD

**Issue by luolong** [lkishalmi/gradle-gatling-plugin#90]
It seems that this plug-in has hard coded simulations source folder set to `src/gatling/simulations`.

I have a legacy code layout where `src` folder is already taken for Java source code (I am trying to get it untangled, but it takes time to sort these things out) and thus I can not use `src/gatling/simulations` as source folder for simulations.

I tried to re-wire the source location of simulations like this:

```gradle
sourceSets {
  gatiling {
    scala.srcDir "test/gatling/simulations"
    resources.srcDir "test/gatling/resources"
  }
}
```

But it appears that the location `src/gatling/simulations` is [hardwired to the execution path][1] in the extension source.

I'd rather that this would be relative to gatling simulations source folder or there would be some other way to configure this from the build configuration.

[1]: https://github.com/lkishalmi/gradle-gatling-plugin/blob/ff25c5461b25e1e04471a916a72f7af9d2e9535e/src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingPluginExtension.groovy#L51

**Comment by eshepelyuk** [comment]
Well, I see the issue :) Although it's not mentioned explicitely, the source location could be configurable via adjusting `gatling` sourceSet. I'll check what I could do on this.

From the other side, I can't understand the problem you're describing. If you use Gradle and java plugin, the location of java code is `src/main/java` and this path doesn't interfere with the plugin files.

**Comment by luolong** [comment]
So, As described in the original issue description, I have already configured my `gatling` _sourceSet_ to a different location and it compiles just fine. The trouble starts when I try to _*run*_ the simulation.

Running simulations from a _non-standard_ location gives me an error stating that class `....../my/package/MySimulation` can not be found.

The culprint as I've identified (and I admit, I might be missing something) seems to be the following block code in the extension: 

```groovy
class GatlingPluginExtension {
    static final String SIMULATIONS_DIR = "src/gatling/simulations"
    // [...]
    Iterable<String> resolveSimulations(Closure simulationFilter = getSimulations()) {
        def p = this.project
        project.sourceSets.gatling.allScala.matching(simulationFilter).collect { File simu ->
            Paths.get(p.file(SIMULATIONS_DIR).toURI()).relativize(Paths.get(simu.toURI())).join(".") - ".scala"
        }
    }
}
```

This will use `src/gatling/simulations` as a global base directory for resolving the path to the simulation file and yields this weird class name.

> From the other side, I can't understand the problem you're describing. If you use Gradle and java plugin, the location of java code is src/main/java and this path doesn't interfere with the plugin files.

This is true for the usual conventional project set-up, but this in NOT the project set-up that I am working with right now. The project has been converted from an old ANT project a long time ago (with Java sources starting at `src/`) and has accumulated a lot of extra configuration cruft that make the build file rather cumbersome.

I am trying to unf*ck this, but this is an ongoing process and not something that can be moved overnight.

**Comment by eshepelyuk** [comment]
@luolong - no need to describe an issue several times, the reason is clear from the 1st time and I'll try to take care of it this week.

For the gatling source location issue - maybe it worth to move gatling codebase to another repository ? So you will separate legacy codebase from new gatling project

**Comment by eshepelyuk** [comment]
@luolong can you chat me in gitter plz ?

**Comment by eshepelyuk** [comment]
Released in Release #3.2.2. Please feedback.

**Comment by luolong** [comment]
Great!

I'll check this soon.

**Comment by eshepelyuk** [comment]
Unfortunately 3.2.2 is not yet published on gradle plugin portal, let's wait

**Comment by eshepelyuk** [comment]
Fixed in 

https://github.com/lkishalmi/gradle-gatling-plugin/releases/tag/3.2.7

https://plugins.gradle.org/plugin/com.github.lkishalmi.gatling/3.2.7

**Comment by eshepelyuk** [comment]
@luolong did it solve the issue ?

**Comment by luolong** [comment]
I'm sorry, I am working on something else at the moment, so I will have to come back to this in few days.
