### ISSUE TITLE
Setting scalaVersion breaks gatlingRun

### ISSUE THREAD

**Issue by zeburek** [lkishalmi/gradle-gatling-plugin#96]
Relates #81 

Made a little investigation. Configuration like this breaks gatlingRun.

Removing `scalaVersion` from configuration and cleaning project makes it run again.

It seems that `scalaVersion` works wrong way. Tested on Gradle 5.3 and 4.10

```gradle
plugins {
    id "com.github.lkishalmi.gatling" version "3.2.9"
}

repositories {
    mavenCentral()
}

group 'test'
version '0.0.1'

apply plugin: 'scala'

dependencies {
    compile 'org.scala-lang:scala-library:2.13.1'
}

gatling {
    toolVersion = '3.2.1'
    scalaVersion = '2.13.1'
    includeMainOutput = false
    includeTestOutput = false
}
```

**Comment by zeburek** [comment]
> Gatling doesn't support Scala 2.13.

Where I can get this information?

**Comment by slandelle** [comment]
https://github.com/gatling/gatling/issues/3566

**Comment by zeburek** [comment]
Ok, thanks for information
