### ISSUE TITLE
Plugin Installation not clear

### ISSUE THREAD

**Issue by rtriunfo** [lkishalmi/gradle-gatling-plugin#98]
Installation from readme links to https://plugins.gradle.org/plugin/com.github.lkishalmi.gatling but that doesn't contain any steps on installation.

The only info I could find online for installation was from the following blog post https://www.james-willett.com/running-gatling-through-gradle but it's from 2017 and doesn't work with the latest version of the plugin and intellij.

Any chance of an update on the readme installation steps?

**Comment by eshepelyuk** [comment]
![image](https://user-images.githubusercontent.com/1279477/68463360-24048200-0217-11ea-91d1-50305dfc596f.png)
