### ISSUE TITLE
Warning about upcoming incompatibility with Gradle 7

### ISSUE THREAD

**Issue by stefanneuhaus** [lkishalmi/gradle-gatling-plugin#99]
Using the Plugin with Gradle 6 there are Warnings about an upcoming incompatibility with Gradle 7:
```
 ./gradlew --warning-mode all 

> Configure project :
The gatlingCompile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the gatlingImplementation configuration instead.
The gatlingRuntime configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the gatlingRuntimeOnly configuration instead.

[...]

BUILD SUCCESSFUL in 583ms
1 actionable task: 1 executed
```

**Comment by eshepelyuk** [comment]
This issue may require dropping support for `Gradle` <= 4.x, so may take a lot of time to deliver.

**Comment by stefanneuhaus** [comment]
Why is that? Do you mean because of the creation of the configurations "gatlingCompile" and "gatlingImplementation" in [GatlingPlugin](https://github.com/lkishalmi/gradle-gatling-plugin/blob/master/src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingPlugin.groovy#L66)?

If yes, couldn't the configurations be created depending on the actual Gradle version used? This could look similar to the check in [DependencyCheckPlugin](https://github.com/jeremylong/dependency-check-gradle/blob/master/src/main/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPlugin.groovy#L55).

**Comment by stefanneuhaus** [comment]
Any thoughts on to implement Gradle 7 compatibility in the proposed way? If this way is fine for you I could provide a PR.

**Comment by eshepelyuk** [comment]
@stefanneuhaus just try to create a PR and you'll see the issues
this is the branch i've created https://github.com/lkishalmi/gradle-gatling-plugin/tree/issue_99

and this is build results https://travis-ci.org/lkishalmi/gradle-gatling-plugin/builds/610294417

I'd be very appreciated if you will be able to pick up the work and provide complete PR covering this issue without introducing incompatibilities with older versions of `Gradle`

**Comment by eshepelyuk** [comment]
@stefanneuhaus any progress on this ?

**Comment by stefanneuhaus** [comment]
@eshepelyuk I had a quick look at your branch but did not do any actual work, yet. Though I am still confident that the proposed way to fix it will work, I did not yet find the time to properly implement and test it. This requires automatic and manual testing with different Gradle versions. The good news is that you already have compatibility tests that could be extended.

So in short: Yes, I am still willing to provide a fix. But at the moment I cannot make any commitment regarding a due date.

**Comment by eshepelyuk** [comment]
@stefanneuhaus sure, thanks. Just let me know if you'll keep working on this.

**Comment by marcphilipp** [comment]
We're also affected by this. Any updates?

**Comment by eshepelyuk** [comment]
Not from my side.

**Comment by stefanneuhaus** [comment]
Yes, one update from my side. The requirements and focus in our team shifted a bit, which is why we decided to stop using Gatling. Thus the incentive to provide a PR decreased, I must admit.

I am very sorry for that, especially as it was me who brought up the issue and showed willingness to fix it. Still I am convinced that the proposed way will work and that the effort is mainly for thorough testing.

**Comment by marcphilipp** [comment]
I can take a look. What's the minimum version of Gradle that the plugin currently supports? Are there any tests with that version?
